project:
  type: website
  output-dir: docs

website:
  title: "Ian's Webpage"
  navbar:
    left:
      - href: 1/index.qmd
        text: "Page 1"
      - href: 2/index.qmd
        text: "Page 2"

format:
  html:
    theme: journal
    css: styles.css
    toc: true

editor: visual

